name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Clone inlets.dev
        run: |
          git clone --depth=1 https://github.com/inlets/inlets.dev
      - name: Add bundler
        run: |
          sudo gem install bundler:2.2.13
      - name: Installd deps
        run: |
          cd inlets.dev
          bundle install && yarn install
      - name: Build site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build -d docs
