name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone inlets.dev
        run: |
          git clone --depth=1 https://github.com/inlets/inlets.dev
      - name: Build
        run: |
          sudo gem install bundler:2.2.13
          bundle install && yarn install
          JEKYLL_ENV=production bundle exec jekyll build -d docs
